version: "2.2"
services:
  carford:
    container_name: advice_test
    restart: always
    build: .
    ports:
            - "8000:8000"
    command: bash -c "flask drop-db && flask create-db && flask populate-db && flask add-user -u admin -p 1234 && gunicorn carford.wsgi:app --bind=0.0.0.0:8000"

    
