version: "2.2"
services:
  carford:
    container_name: advice_test
    restart: always
    build: .
    ports:
            - "8000:8000"
    command: bash -c "flask create-db && flask populate-db && flask add-user -u admin -p 1234"
    